apiVersion: v1
data:
  username: type_base64_of_JENKINS_USERNAME_here
  token: type_base64_of_JENKINS_TOKEN_here
  hostname: type_base64_of_JENKINS_HOSTNAME_here
kind: Secret
metadata:
  labels:
    app: jenkins-builds-cleaner
  name: jenkins-builds-cleaner
  namespace: jenkins
type: Opaque